# Homebrew Cask for the netscli desktop app (Tauri 2 + React).
#
# Auto-generated by publish-homebrew-cask.sh on every release —
# do not hand-edit. Source template lives in
# netscli's packaging/homebrew/Casks/netscli.rb.

cask "netscli" do
  version "0.2.6"

  on_arm do
    sha256 "faf62fe3f56709b46865a6f35b5bcda4db6a37c4395eb904d1b73214f497e69e"
    url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-gui-macos-aarch64.dmg"
  end
  on_intel do
    sha256 "28354f51e623f9be5a875c6284df9ee1207ae182e0667293475d485a1bb41675"
    url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-gui-macos-x86_64.dmg"
  end

  name "NetsCLI"
  desc "Network scanner desktop app: discover hosts, scan ports, DNS, ARP"
  homepage "https://netscli.com"

  app "NetsCLI.app"

  zap trash: [
    "~/Library/Application Support/com.netscli.app",
    "~/Library/Caches/com.netscli.app",
    "~/Library/Preferences/com.netscli.app.plist",
  ]
end
