# Homebrew Cask for the netscli desktop app (Tauri 2 + React).
#
# Auto-generated by publish-homebrew-cask.sh on every release —
# do not hand-edit. Source template lives in
# netscli's packaging/homebrew/Casks/netscli.rb.

cask "netscli" do
  version "0.2.5"

  on_arm do
    sha256 "89493f2d6e23dfebc2feeb2c3e9badc025adcab882d0a6639990e2b030eb6875"
    url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-gui-macos-aarch64.dmg"
  end
  on_intel do
    sha256 "096b7d3aee5d096d4ac4f947554147b34bb82998c9fa50c8705aa8f04e07c3bb"
    url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-gui-macos-x86_64.dmg"
  end

  name "NetsCLI"
  desc "Network scanner desktop app: discover hosts, scan ports, DNS, ARP"
  homepage "https://netscli.com"

  app "NetsCLI.app"

  zap trash: [
    "~/Library/Application Support/com.netscli.app",
    "~/Library/Caches/com.netscli.app",
    "~/Library/Preferences/com.netscli.app.plist",
  ]
end
