# Formula for Homebrew. After cutting release vX.Y.Z:
# 1. Update `version`.
# 2. Replace the `VERSION_SHA256_*` placeholders with the real SHA256
#    of each platform asset (read from the `.sha256` files on the
#    release page).
# 3. Publish this file in fstubner/homebrew-tap (or submit to
#    homebrew-core once the project has a few releases under its belt).
#
# Usage after tap is published:
#   brew tap fstubner/tap
#   brew install netscli

class Netscli < Formula
  desc "Network scanner with CLI, TUI, desktop app, and MCP server"
  homepage "https://netscli.com"
  version "0.2.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-macos-aarch64"
      sha256 "82b13af00286a3f9bef1a7be105dafeca039ab695851b07e4628498b339a78fb"
    end
    on_intel do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-macos-x86_64"
      sha256 "9a0f871ce0ad02f6c7e68aef430182a502dd8868ecd669a2fdd2a2dcec9868d9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-linux-aarch64"
      sha256 "dddacc7a45463da598639509e709a791a60c0467f2ed43c3607384f8d982328a"
    end
    on_intel do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-linux-x86_64"
      sha256 "4e4677ce243ee8eefb069f8c0f35aec1a15aa9515c2aff27b75f08c3de586744"
    end
  end

  def install
    # Asset is the bare binary — rename and mark executable.
    asset_name = if OS.mac?
      Hardware::CPU.arm? ? "netscli-macos-aarch64" : "netscli-macos-x86_64"
    else
      Hardware::CPU.arm? ? "netscli-linux-aarch64" : "netscli-linux-x86_64"
    end
    bin.install asset_name => "netscli"

    # Shell completions + man page generated by the binary itself.
    generate_completions_from_executable(bin/"netscli", "completions")
    (buildpath/"netscli.1").write Utils.safe_popen_read(bin/"netscli", "man")
    man1.install "netscli.1"
  end

  test do
    assert_match "netscli #{version}", shell_output("#{bin}/netscli --version")
  end
end
