# Formula for Homebrew. After cutting release vX.Y.Z:
# 1. Update `version`.
# 2. Replace the `VERSION_SHA256_*` placeholders with the real SHA256
#    of each platform asset (read from the `.sha256` files on the
#    release page).
# 3. Publish this file in fstubner/homebrew-tap (or submit to
#    homebrew-core once the project has a few releases under its belt).
#
# Usage after tap is published:
#   brew tap fstubner/tap
#   brew install netscli

class Netscli < Formula
  desc "Network scanner with CLI, TUI, desktop app, and MCP server"
  homepage "https://netscli.com"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-macos-aarch64"
      sha256 "0d159cf512df01253d2e202fcae47cb03e5c40a470a2bd7c6668173ee8ab6b76"
    end
    on_intel do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-macos-x86_64"
      sha256 "009910f9fbe56775ec906c1096ed6009521d5802215ce72d9ffdd49ddda8faea"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-linux-aarch64"
      sha256 "d5444079cf3bf75aa5459c1bcedd2e70a161fb76e1be1b1348b307a79b7b8e65"
    end
    on_intel do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-linux-x86_64"
      sha256 "e19d627c95e852536df9e9dace1d21ced70c1510e961a1bb39f4c29c65f61045"
    end
  end

  def install
    # Asset is the bare binary — rename and mark executable.
    asset_name = if OS.mac?
      Hardware::CPU.arm? ? "netscli-macos-aarch64" : "netscli-macos-x86_64"
    else
      Hardware::CPU.arm? ? "netscli-linux-aarch64" : "netscli-linux-x86_64"
    end
    bin.install asset_name => "netscli"

    # Shell completions + man page generated by the binary itself.
    generate_completions_from_executable(bin/"netscli", "completions")
    (buildpath/"netscli.1").write Utils.safe_popen_read(bin/"netscli", "man")
    man1.install "netscli.1"
  end

  test do
    assert_match "netscli #{version}", shell_output("#{bin}/netscli --version")
  end
end
