# Formula for Homebrew. After cutting release vX.Y.Z:
# 1. Update `version`.
# 2. Replace the `VERSION_SHA256_*` placeholders with the real SHA256
#    of each platform asset (read from the `.sha256` files on the
#    release page).
# 3. Publish this file in fstubner/homebrew-tap (or submit to
#    homebrew-core once the project has a few releases under its belt).
#
# Usage after tap is published:
#   brew tap fstubner/tap
#   brew install netscli

class Netscli < Formula
  desc "Network scanner with CLI, TUI, desktop app, and MCP server"
  homepage "https://netscli.com"
  version "0.2.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-macos-aarch64"
      sha256 "2a34d475420bed4181b52decd0d2a43f0c8bf638d6ed14e529dc1f4fd389d70b"
    end
    on_intel do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-macos-x86_64"
      sha256 "4c3041d99291a9778e6b87e0f47d041cd9044fcd1b762ddb80dd9dac5fed2866"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-linux-aarch64"
      sha256 "9673312f500dbe55e1ab90961c115aff3f52490c7125322378f6df96bc5dbd35"
    end
    on_intel do
      url "https://github.com/fstubner/netscli/releases/download/v#{version}/netscli-linux-x86_64"
      sha256 "08f3fff593ed82a10d6abc53435baaf51e63e3d9c48af90254257e08071f751d"
    end
  end

  def install
    # Asset is the bare binary — rename and mark executable.
    asset_name = if OS.mac?
      Hardware::CPU.arm? ? "netscli-macos-aarch64" : "netscli-macos-x86_64"
    else
      Hardware::CPU.arm? ? "netscli-linux-aarch64" : "netscli-linux-x86_64"
    end
    bin.install asset_name => "netscli"

    # Shell completions + man page generated by the binary itself.
    generate_completions_from_executable(bin/"netscli", "completions")
    (buildpath/"netscli.1").write Utils.safe_popen_read(bin/"netscli", "man")
    man1.install "netscli.1"
  end

  test do
    assert_match "netscli #{version}", shell_output("#{bin}/netscli --version")
  end
end
